export const tableHeaders = [
  { field: 'planNumber', headerName: '№ плана' },
  { field: 'semesterNumber', headerName: 'Семестр' },
  { field: 'educationForm', headerName: 'Форма обучения' },
  { field: 'group', headerName: 'Группа' },
  { field: 'flowNumber', headerName: '№ потока' },
  { field: 'subject', headerName: 'Дисциплина' },
  {
    field: 'cathedra',
    headerName: 'Кафедра',
    type: 'editableColumn',
    cellEditor: 'agRichSelectCellEditor',
    cellEditorPopup: true,
    cellEditorParams: {
      values: ['ИСИТ', 'АПП'],
      cellEditorPopup: true,
    },
  },
  { field: 'specialtyId', headerName: 'Специальность' },
  { field: 'course', headerName: 'Курс' },
  { field: 'studentsCounter', headerName: 'Студентов' },
  { field: 'subgroupNumber', headerName: 'Количество подгрупп' },
  { field: 'lectures', headerName: 'Лекции' },
  { field: 'practices', headerName: 'Практики' },
  { field: 'labs', headerName: 'Лабораторные' },
  { field: 'consultation', headerName: 'Консультации' },
  { field: 'exams', headerName: 'Экзамены' },
  { field: 'view', headerName: 'Просмотр' },
  { field: 'diffOffset', headerName: 'Диф.зачёт' },
  { field: 'offset', headerName: 'Зачёт' },
  { field: 'rgr', headerName: 'РГР' },
  { field: 'practiceGuidance', headerName: 'Руководство практикой' },
  { field: 'courseWork', headerName: 'Курсовая работа' },
  { field: 'courseProject', headerName: 'Курсовой проект' },
  { field: 'controlWork', headerName: 'Контр. раб.' },
  { field: 'diplomaDesign', headerName: 'Дипломное проектирование' },
  { field: 'gek', headerName: 'ГЭК' },
  { field: 'otherWork', headerName: 'Прочие работы' },
];

export const fakeRowData = [
  {
    planNumber: 21,
    semesterNumber: 3,
    educationForm: 'Дневная',
    group: 'Ит-5',
    flowNumber: 2,
    cathedra: null,
    subject:
      'Базы знаний и поддержка принятия решений в системах автоматизированного проектирования',
    specialtyId: '1-40 05 01-01',
    course: 2,
    studentsCounter: 28,
    subgroupNumber: 2,
    lectures: 32,
    practices: null,
    labs: 64,
    consultation: 5.23,
    exams: null,
    view: null,
    diffOffset: null,
    offset: 7.25,
    rgr: null,
    practiceGuidance: null,
    courseWork: null,
    courseProject: null,
    controlWork: null,
    diplomaDesign: null,
    gek: null,
    otherWork: null,
  },
  {
    id: 2,
    planNumber: 21,
    semesterNumber: 3,
    educationForm: 'Дневная',
    group: 'Ит-10',
    flowNumber: 2,
    cathedra: null,
    subject:
      'Базы знаний и поддержка принятия решений в системах автоматизированного проектирования',
    specialtyId: '1-40 05 01-01',
    course: 2,
    studentsCounter: 28,
    subgroupNumber: 2,
    lectures: 32,
    practices: null,
    labs: 64,
    consultation: 5.23,
    exams: null,
    view: null,
    diffOffset: null,
    offset: 7.25,
    rgr: null,
    practiceGuidance: null,
    courseWork: null,
    courseProject: null,
    controlWork: null,
    diplomaDesign: null,
    gek: null,
    otherWork: null,
  },
];
